#!/bin/bash
if [[ $(realpath "$PWD") == /mnt/c/* ]]; then
  GIT_REVIEW_PATH_W10=$(which git-review.exe)
  if [ -n "${GIT_REVIEW_PATH_W10}" ]; then
	  "${GIT_REVIEW_PATH_W10}" "$@"
	else
	  /usr/bin/git-review "$@"
	fi
else
	/usr/bin/git-review "$@"
fi
