#!/bin/bash

REAL_PATH=$(realpath "$PWD")
if [[ "$REAL_PATH" == /mnt/c/* ]]; then
	if [[ "$REAL_PATH" == "$PWD" ]]; then
		cd "$REAL_PATH" || exit 1
	fi
	exec "/mnt/c/Program Files/Git/cmd/git.exe" "$@"
else
	exec /usr/bin/git "$@"
fi
