#!/bin/bash
if [[ $(realpath "$PWD") == /mnt/c/* ]]; then
  WHERE_PATH=$(/mnt/c/Windows/System32/where.exe git-review)
  if [ "$?" -eq 0 ]; then
    GIT_REVIEW_PATH_W10=$(wslpath -a "${WHERE_PATH}" | sed 's/\r*$//g')
	  $GIT_REVIEW_PATH_W10 "$@"
	else
	  /usr/bin/git-review "$@"
	fi
else
	/usr/bin/git-review "$@"
fi
