#!/usr/bin/env bash

BASE_DIR=$(dirname $(realpath $0))
DIRECTORY=$(basename "$(pwd -P)")

if [ "$DIRECTORY" != "extensions" ]; then
	echo "This script only runs in the 'extensions' directory" >&2
	exit 127
fi

mapfile -t WMF_REPO_NAMES < <("${BASE_DIR}/list-extensions" wmf)
mapfile -t REPO_NAMES_MATCH < <(
	grep -rls --exclude-dir=".git" "$@" "${WMF_REPO_NAMES[@]}" | \
	grep -Po '^[^/]+' | \
	uniq
)
for REPO_NAME in "${REPO_NAMES_MATCH[@]}"; do
	OUT=$(grep -r --exclude-dir=".git" --color=always -hn "$@" "$REPO_NAME")
	[ -z "$OUT" ] || echo -e "$REPO_NAME:\n$OUT"
done
