#!/usr/bin/env bash

WMF_EXTS_URL="https://raw.githubusercontent.com/wikimedia/OPERATIONs-mediawiki-config/master/wmf-config/extension-list"
CACHE_FILE="$HOME/.WMF_MEDIAWIKI_EXTENSION_LIST"

DIRECTORY=$(basename "$(pwd -P)")

if [ "$DIRECTORY" != "extensions" ]; then
	echo "This script only runs in the 'extensions' directory" >&2
	exit 127
fi

if [ -n $(find "$CACHE_FILE" -maxdepth 0 -mmin -120 -size +1k 2>/dev/null) ]; then
	# Exclude nested repositories for directory layout sanity
	# shellcheck disable=SC2016
	wget -qO- "$WMF_EXTS_URL" | grep -P '^\$IP/extensions/[^/]+/[^/]+$' |
		awk -F/ '{print $3}' \
		>"${CACHE_FILE}"
	[ $? -eq 0 ] || exit $?
fi

mapfile -t REPO_NAMES <"$CACHE_FILE"
mapfile -t REPO_NAMES_MATCH < <(
	grep -rls --exclude-dir=".git" "$@" "${REPO_NAMES[@]}" | \
	grep -Po '^[^/]+' | \
	uniq
)
for REPO_NAME in "${REPO_NAMES_MATCH[@]}"; do
	OUT=$(grep -r --exclude-dir=".git" --color=always -hn "$@" "$REPO_NAME")
	[ -z "$OUT" ] || echo -e "$REPO_NAME:\n$OUT"
done
