#!/bin/bash
mapfile -t FILES < <(git diff --name-only --oneline origin..HEAD)
for FILE in "${FILES[@]}"; do
	echo "Checking ${FILE}..."
	"/home/aaron/.config/composer/vendor/bin/phan_client" -l "${FILE}"
done
