#!/usr/bin/env bash

REAL_PATH=$(realpath "$0")
CORE_UTILS_DIR=$(dirname "$REAL_PATH")
BASE_DIR=$(dirname "$CORE_UTILS_DIR")

function sync_srv_mediawiki() {
	# Make sure ~/bin/git is used for Linux/WIN32 executable selection
	sudo -u www-data --preserve-env=DEV_MW_DIR,SRV_MW_DIR "${BASE_DIR}/utils/sync-srv-mediawiki"
}

sync_srv_mediawiki || exit $?
vendor/bin/phan -d /srv/mediawiki/core -p
