#!/bin/bash

NODE=$1
shift

if [ -z "${NODE}" ]; then
	echo "Usage: mmariadb <group suffix> <mariadb arguments>"
	exit 1;
fi

if [ ! -f "/etc/mysql/${NODE}.cnf" ]; then
	echo "Could not find /etc/mysql/${NODE}.cnf"
	exit 1;
fi

sudo mariadb --defaults-group-suffix=".${NODE}" "$@"
