#!/bin/bash

REAL_PATH=$(realpath "$0")
BASE_DIR=$(dirname "$REAL_PATH")
NODES=("db1 db2 db3")
PRIMARY_NODE="db1"
REPLICA_NODES=("db2 db3")

PASS=$1
if [ -z "${PASS}" ]; then
  echo "Usage: enable_replicated_multi_mariadb <REPLICATION USER PASSWORD>"
  exit 1
fi

cd ~

for NODE in $NODES; do
  sudo systemctl start "mariadb@${NODE}.service" || exit $?
done

echo "Configuring database for ptheartbeat on ${PRIMARY_NODE}..."
echo "CREATE DATABASE IF NOT EXISTS heartbeat;" | sudo mariadb --defaults-group-suffix=".${PRIMARY_NODE}" -B || exit $?

echo "Configuring grants for repl on ${PRIMARY_NODE}..."
echo "CREATE USER IF NOT EXISTS 'repl'@'127.0.0.1' IDENTIFIED BY '${PASS}'; GRANT REPLICATION SLAVE ON *.* TO 'repl'@'127.0.0.1';" | sudo mariadb --defaults-group-suffix=".${PRIMARY_NODE}" -B || exit $?

echo "Configuring grants for ptheartbeat on ${PRIMARY_NODE}..."
echo "CREATE USER IF NOT EXISTS 'ptheartbeat'@'127.0.0.1' IDENTIFIED BY '${PASS}'; GRANT REPLICATION CLIENT, SLAVE MONITOR ON *.* TO 'ptheartbeat'@'127.0.0.1'; GRANT CREATE, INSERT, UPDATE, SELECT ON heartbeat.* TO 'ptheartbeat'@'127.0.0.1';" | sudo mariadb --defaults-group-suffix=".${PRIMARY_NODE}" -B || exit $?

# pt-heartbeat -D heartbeat -h 127.0.0.1 -P 3316 --update --create-table --user ptheartbeat --password ${PASS} --interval 0.25 --utc --daemonize

echo "Getting GTID info for ${PRIMARY_NODE}..."
GTID_MASTER_POS=$(echo "select @@gtid_current_pos" | sudo mariadb --defaults-group-suffix=".${PRIMARY_NODE}" -B | tail -n 1)
if [ -z "${GTID_MASTER_POS}" ]; then
  echo "Could not get gtid_current_pos"
  exit 1
fi
echo "========== ${PRIMARY_NODE} ========== "
echo "show variables like '%gtid%';" | sudo mariadb --defaults-group-suffix=".${PRIMARY_NODE}" -B || exit $?
echo "=========="
echo "Using master GTID pos '${GTID_MASTER_POS}'"

for NODE in $REPLICA_NODES; do
  READ_ONLY=$(echo "select @@read_only" | sudo mariadb --defaults-group-suffix=".${NODE}" -B | tail -n 1)
  if [ "${READ_ONLY}" -eq 1 ]; then
    echo ""
    echo "Server ${NODE} is read only, checking replication status...";
    echo "SHOW REPLICA STATUS\G" | sudo mariadb --defaults-group-suffix=".${NODE}" -B || exit $?
    echo "...skipped server ${NODE}"
    continue;
  fi

  echo "Enabling semi-sync replication on ${NODE}..."
  echo "SET GLOBAL rpl_semi_sync_slave_enabled=ON;" | sudo mariadb --defaults-group-suffix=".${NODE}" -B || exit $?

  echo "Resetting/stopping any replication on ${NODE}..."
  echo "STOP SLAVE; RESET SLAVE;" | sudo mariadb --defaults-group-suffix=".${NODE}" -B || exit $?

  echo "Configuring replication on ${NODE}..."
  echo "SET GLOBAL gtid_slave_pos = '${GTID_MASTER_POS}';" | sudo mariadb --defaults-group-suffix=".${NODE}" -B || exit $?
  echo "========== ${NODE} ========== "
  echo "show variables like '%gtid%';" | sudo mariadb --defaults-group-suffix=".${NODE}" -B || exit $?
  echo "=========="
  echo "CHANGE MASTER TO MASTER_HOST='127.0.0.1', MASTER_PORT=3316, MASTER_USER='repl', MASTER_PASSWORD='${PASS}', MASTER_USE_GTID=slave_pos;" | sudo mariadb --defaults-group-suffix=".${NODE}" -B

  echo "Starting replication on ${NODE}..."
  echo "START SLAVE;" | sudo mariadb --defaults-group-suffix=".${NODE}" -B || exit $?
  echo "SET GLOBAL READ_ONLY = ON;" | sudo mariadb --defaults-group-suffix=".${NODE}" -B || exit $?
  echo "SHOW REPLICA STATUS\G" | sudo mariadb --defaults-group-suffix=".${NODE}" -B || exit $?
done

echo "Enabling semi-sync replication on ${PRIMARY_NODE}..."
echo "SET GLOBAL rpl_semi_sync_master_enabled=ON;" | sudo mariadb --defaults-group-suffix=".${PRIMARY_NODE}" -B || exit $?
