#!/bin/bash

REAL_PATH=$(realpath "$0")
BASE_DIR=$(dirname "$REAL_PATH")
NODES=("db1 db2 db3 db4")
PRIMARY_NODE="db1"
REPLICA_NODES=("db2 db3 db4")

USER=$1
HOSTNAME=$2
if [ -z "${USER}" -o -z "${HOSTNAME}" ]; then
  echo "Usage: grant_replicat_monitor <USERNAME> <HOSTNAME>"
  exit 1
fi

cd ~

echo "GRANT SLAVE MONITOR ON *.* TO '${USER}'@'${HOSTNAME}';" | sudo mariadb --defaults-group-suffix=".${PRIMARY_NODE}"
echo "GRANT BINLOG MONITOR ON *.* TO '${USER}'@'${HOSTNAME}';" | sudo mariadb --defaults-group-suffix=".${PRIMARY_NODE}"
