#!/bin/bash

REAL_PATH=$(realpath "$0")
BASE_DIR=$(dirname "$REAL_PATH")
NODES=("db1 db2 db3 db4")

RESET=0
if [ "$1" == "reset" ]; then
  RESET=1;
fi

cd ~

if grep "\[mysqld\]" "/etc/mysql/mariadb.conf.d/50-server.cnf"; then
  echo "The stock server must be moved to a group (e.g. [mysqld.main])"
  exit 1
fi

for NODE in $NODES; do
  echo "Unregistering/stopping any prior ${NODE} service..."
  sudo systemctl stop "mariadb@${NODE}.service"
  sudo systemctl disable "mariadb@${NODE}.service"

  if [ $RESET -eq 1 ]; then
    echo "Clearing ${NODE} directories"
    sudo rm -rf "/var/lib/mysql-multi/${NODE}" || exit $?
    sudo rm -rf "/var/log/mysql-multi/${NODE}" || exit $?
  fi
done

echo 'Setting multi-instance directories...'
if [ ! -d "/var/lib/mysql-multi" ]; then
  sudo mkdir "/var/lib/mysql-multi" || exit $?
  sudo chown -R mysql:mysql "/var/lib/mysql-multi" || exit $?
fi
if [ ! -d "/var/log/mysql-multi" ]; then
  sudo mkdir "/var/log/mysql-multi" || exit $?
  sudo chown -R mysql:adm "/var/log/mysql-multi" || exit $?
fi
if [ ! -d "/run/mysql-multi" ]; then
  sudo mkdir "/run/mysql-multi" || exit $?
  sudo chown -R mysql:mysql "/run/mysql-multi" || exit $?
fi
for NODE in $NODES; do
  if [ ! -d "/var/lib/mysql-multi/${NODE}" ]; then
    sudo mkdir "/var/lib/mysql-multi/${NODE}" || exit $?
    sudo chown -R mysql:adm "/var/lib/mysql-multi/${NODE}" || exit $?
  fi
  if [ ! -d "/var/log/mysql-multi/${NODE}" ]; then
    sudo mkdir "/var/log/mysql-multi/${NODE}" || exit $?
    sudo chown -R mysql:adm "/var/log/mysql-multi/${NODE}" || exit $?
  fi
done

# See /lib/systemd/system/mariadb@.service
echo 'Setting multi-instance config...'
sudo echo -n > "multi-server-client.cnf"
for NODE in $NODES; do
  NODE_ID=$(echo "${NODE}" | grep -Po '\d+$')
  sed -e "s/#NODE#/${NODE}/g;s/#NODE_ID#/${NODE_ID}/g;s/#NODE_SECTION#/${NODE}/g" "${BASE_DIR}/server-client-NODE.cnf" >> "multi-server-client.cnf" || exit $?
  sed -e "s/#NODE#/${NODE}/g;s/#NODE_ID#/${NODE_ID}/g;s/.#NODE_SECTION#//g" "${BASE_DIR}/server-client-NODE.cnf" > "${NODE}.cnf" || exit $?
  sudo cp "${NODE}.cnf" "/etc/mysql/" || exit $?
done
sudo cp "multi-server-client.cnf" "/etc/mysql/conf.d/100-multi-server-client.cnf" || exit $?

for NODE in $NODES; do
  if [ ! -f "/var/lib/mysql-multi/${NODE}/ibdata1" ]; then
    echo "Installing ${NODE} instance..."
    if ! my_print_defaults -g ".${NODE}" --mysqld | grep "datadir=/var/lib/mysql-multi/${NODE}"; then
      echo "Group configuration test failed: group section config absent!";
      exit 1
    fi
    if my_print_defaults -g ".${NODE}" --mysqld | grep "/run/mysqld/mysqld.sock"; then
      echo "Group configuration test failed: bogus stock config present!";
      exit 1
    fi
    sudo mariadb-install-db --defaults-group-suffix=".${NODE}" --datadir="/var/lib/mysql-multi/${NODE}" || exit $?
  fi
done

for NODE in $NODES; do
  echo "Registering ${NODE} service..."
  sudo systemctl enable "mariadb@${NODE}.service"|| exit $?
  if ! sudo systemctl start "mariadb@${NODE}.service"; then
    CODE=$?
    sudo systemctl status "mariadb@${NODE}.service" --no-pager
    if [ -f "/var/log/mysql-multi/${NODE}/error.log" ]; then
      echo ''
      sudo tail -n 30 "/var/log/mysql-multi/${NODE}/error.log"
    fi
    exit $CODE
  fi
done
