#!/bin/bash

REAL_PATH=$(realpath "$0")
BASE_DIR=$(dirname "$REAL_PATH")
NODES=("db1 db2 db3 db4")

cd ~

if [ ! -d "/var/lib/mysql-multi" ]; then
  sudo mkdir "/var/lib/mysql-multi"
  sudo chown -R mysql "/var/lib/mysql-multi"
fi
if [ ! -d "/var/log/mysql-multi" ]; then
  sudo mkdir "/var/log/mysql-multi"
  sudo chown -R mysql "/var/log/mysql-multi"
fi

# See /lib/systemd/system/mariadb@.service
echo 'Setting multi-instance config...'
sudo echo -n > "multi-server-client.cnf"
for NODE in $NODES; do
  NODE_ID=$(echo "${NODE}" | grep -Po '\d+$')
  sed -e "s/#NODE#/${NODE}/g;s/#NODE_ID#/${NODE_ID}/g;s/#NODE_SECTION#/${NODE}/g" "${BASE_DIR}/server-client-NODE.cnf" >> "multi-server-client.cnf" || exit $?
  sed -e "s/#NODE#/${NODE}/g;s/#NODE_ID#/${NODE_ID}/g;s/.#NODE_SECTION#//g" "${BASE_DIR}/server-client-NODE.cnf" > "${NODE}.cnf" || exit $?
  sudo cp "${NODE}.cnf" "/etc/mysql/" || exit $?
done
sudo cp "multi-server-client.cnf" "/etc/mysql/conf.d/100-multi-server-client.cnf" || exit $?
echo 'Config setting done'

for NODE in $NODES; do
  sudo systemctl stop "mariadb@${NODE}.service"
  sudo systemctl disable "mariadb@${NODE}.service"

  if [ ! -d "/var/lib/mysql-multi/${NODE}" ]; then
    sudo mkdir "/var/lib/mysql-multi/${NODE}"
    sudo chown -R mysql "/var/lib/mysql-multi/${NODE}"
    sudo chgrp mysql "/var/lib/mysql-multi/${NODE}"
  fi
  sudo rm -rf "/var/lib/mysql-multi/${NODE}/*"

  if [ ! -d "/var/log/mysql-multi/${NODE}" ]; then
    sudo mkdir "/var/log/mysql-multi/${NODE}"
    sudo chown -R mysql "/var/log/mysql-multi/${NODE}"
    sudo chgrp mysql "/var/log/mysql-multi/${NODE}"
  fi
  sudo rm -rf "/var/log/mysql-multi/${NODE}/*"

  echo "Installing ${NODE} instance..."
  sudo mariadb-install-db --user=mysql --datadir="/var/lib/mysql-multi/${NODE}" --defaults-group-suffix=".${NODE}" || exit $?
  sudo systemctl enable "mariadb@${NODE}.service"
  sudo systemctl start "mariadb@${NODE}.service"
  wait
  echo "Installation done"
done

"${BASE_DIR}"/setup_mariadb_replication.sh

echo "Please comment out <<socket=/run/mysqld/mysqld.sock>> in /etc/mysql/mariadb.cnf
#sudo systemctl stop mariadb; sudo killall mariadbd; sudo rm -rf /var/lib/mysql; sudo rm -rf /var/log/mysql/*; sudo mariadb-install-db --user=mysql --datadir="/var/lib/mysql"; sudo systemctl start mariadb
