#!/bin/bash

REAL_PATH=$(realpath "$0")
BASE_DIR=$(dirname "$REAL_PATH")
NODES=("db1 db2 db3 db4")

RESET=0
if [ "$1" == "reset" ]; then
  RESET=1;
fi

cd ~

if [ grep "\[mysqld\]" "/etc/mysql/mariadb.conf.d/50-server.cnf" ]; then
  echo "The stock server must be moved to a group (e.g. [mysqld.main])"
  exit 1
fi

echo 'Setting multi-instance directories...'
if [ ! -d "/var/lib/mysql-multi" ]; then
  sudo mkdir "/var/lib/mysql-multi" || exit $?
  sudo chown -R mysql:mysql "/var/lib/mysql-multi" || exit $?
fi
if [ ! -d "/var/log/mysql-multi" ]; then
  sudo mkdir "/var/log/mysql-multi" || exit $?
  sudo chown -R mysql:mysql "/var/log/mysql-multi" || exit $?
fi
echo 'Directory setting done'

# See /lib/systemd/system/mariadb@.service
echo 'Setting multi-instance config...'
sudo echo -n > "multi-server-client.cnf"
for NODE in $NODES; do
  NODE_ID=$(echo "${NODE}" | grep -Po '\d+$')
  sed -e "s/#NODE#/${NODE}/g;s/#NODE_ID#/${NODE_ID}/g;s/#NODE_SECTION#/${NODE}/g" "${BASE_DIR}/server-client-NODE.cnf" >> "multi-server-client.cnf" || exit $?
  sed -e "s/#NODE#/${NODE}/g;s/#NODE_ID#/${NODE_ID}/g;s/.#NODE_SECTION#//g" "${BASE_DIR}/server-client-NODE.cnf" > "${NODE}.cnf" || exit $?
  sudo cp "${NODE}.cnf" "/etc/mysql/" || exit $?
done
sudo cp "multi-server-client.cnf" "/etc/mysql/mariadb.conf.d/70-multi-server-client.cnf" || exit $?
echo 'Config setting done'

for NODE in $NODES; do
  echo "Unregistering/stopping any prior ${NODE} service..."
  sudo systemctl stop "mariadb@${NODE}.service"
  sudo systemctl disable "mariadb@${NODE}.service"
  echo "Service unregister done"

  echo "Setting ${NODE} directories"
  if [ ! -d "/var/lib/mysql-multi/${NODE}" ]; then
    sudo mkdir "/var/lib/mysql-multi/${NODE}" || exit $?
    sudo chown -R mysql:mysql "/var/lib/mysql-multi/${NODE}" || exit $?
  fi
  if [ ! -d "/var/log/mysql-multi/${NODE}" ]; then
    sudo mkdir "/var/log/mysql-multi/${NODE}" || exit $?
    sudo chown -R mysql:mysql "/var/log/mysql-multi/${NODE}" || exit $?
  fi
  echo 'Directory setting done'

  if [ "${RESET}" -eq 1 ]; then
    echo "Clearing ${NODE} directories"
    sudo rm -rf "/var/lib/mysql-multi/${NODE}/*" || exit $?
    sudo rm -rf "/var/log/mysql-multi/${NODE}/*" || exit $?
    echo "Done clearing directories"
  fi

  if [ ! -f "/var/lib/mysql-multi/${NODE}/ibdata1" ]; then
    echo "Installing ${NODE} instance..."
    if ! my_print_defaults -g .db1 --mysqld | grep "{$NODE}"; then
      echo "Group configuration test failed: group section config absent!";
      exit 1
    fi
    if my_print_defaults -g .db1 --mysqld | grep "/run/mysqld/mysqld.sock"; then
      echo "Group configuration test failed: bogus stock config present!";
      exit 1
    fi
    sudo mariadb-install-db --user=mysql --datadir="/var/lib/mysql-multi/${NODE}" --defaults-group-suffix=".${NODE}" || exit $?
    echo "Installation done"
  fi

  echo "Registering ${NODE} service..."
  sudo systemctl enable "mariadb@${NODE}.service"|| exit $?
  sudo systemctl start "mariadb@${NODE}.service" && wait
  echo "Service register/start done"
done

#sudo systemctl stop mariadb; sudo killall mariadbd; sudo rm -rf /var/lib/mysql; sudo rm -rf /var/log/mysql/*; sudo mariadb-install-db --user=mysql --datadir="/var/lib/mysql"; sudo systemctl start mariadb
