#!/usr/bin/env sh

# Avoid shelling out to basename
COMMAND="${0##*/}"

# Use the "Git for Windows" program if $PWD belongs to Windows
case "$(pwd -P)" in /mnt/[cde]/*)
    BIN_PATH="/mnt/c/Program Files/Git/usr/bin/$COMMAND.exe"
    [ ! -x "$BIN_PATH" ] || exec "$BIN_PATH" "$@"
    ;;
esac
# Otherwise, use the Linux program (custom => distribution => pre-init utils)
for BIN_DIR in "/usr/local/bin" "/usr/bin"; do
    [ ! -x "$BIN_DIR/$COMMAND" ] || exec "$BIN_DIR/$COMMAND" "$@"
done
exec "/bin/$COMMAND" "$@"
